# Zeabur部署配置
name: xiaohongshu-proxy

# 服务配置
services:
  # 主应用服务
  app:
    # 构建配置
    build:
      dockerfile: Dockerfile.zeabur

    # 环境变量
    env:
      - PORT=8080
      - APP_ENV=production
      - LOG_LEVEL=info
      - DB_HOST=${POSTGRESQL_HOST}
      - DB_PORT=${POSTGRESQL_PORT}
      - DB_USER=${POSTGRESQL_USERNAME}
      - DB_PASSWORD=${POSTGRESQL_PASSWORD}
      - DB_NAME=${POSTGRESQL_DATABASE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

    # 端口映射
    ports:
      - "8080:8080"

    # 健康检查
    healthcheck:
      http_get:
        path: /health
        port: 8080
      initial_delay_seconds: 30
      period_seconds: 10

    # 依赖服务
    depends_on:
      - postgres
      - redis

  # PostgreSQL数据库
  postgres:
    image: postgres:15-alpine
    env:
      - POSTGRES_DB=xiaohongshu_proxy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}

    # 数据持久化
    volumes:
      - postgres_data:/var/lib/postgresql/data

    # 端口
    ports:
      - "5432:5432"

  # Redis缓存
  redis:
    image: redis:7-alpine
    env:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

    # 数据持久化
    volumes:
      - redis_data:/data

    # 端口
    ports:
      - "6379:6379"

# 数据卷
volumes:
  postgres_data:
  redis_data:

# 域名配置（可选）
domains:
  - xiaohongshu-proxy.zeabur.app