# Zeabur部署专用配置
app:
  name: "xiaohongshu-proxy"
  version: "1.0.0"
  environment: "production"
  host: "0.0.0.0"
  port: 8080

# 使用PostgreSQL数据库
database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "your-db-password"  # 会被环境变量覆盖
  name: "xiaohongshu_proxy"
  ssl_mode: "disable"
  max_connections: 25
  max_idle_connections: 5

# Redis配置（Zeabur会自动提供）
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10

# JWT配置
jwt:
  secret: "change-this-in-production"  # 会被环境变量覆盖
  expires_in: 24h

# Claude API配置
claude:
  api_key: "your-claude-api-key"  # 会被环境变量覆盖
  base_url: "https://api.anthropic.com"
  timeout: 30s
  max_retries: 3

# MCP配置
mcp:
  base_url: "http://localhost:3001"  # 小红书MCP服务地址
  timeout: 30s
  max_connections: 10

# 容器配置
container:
  registry: "docker.io"
  base_port: 3000
  max_per_user: 5
  auto_cleanup: true
  cleanup_interval: 1h

# 日志配置
logging:
  level: "info"
  format: "json"
  output: "stdout"

# 安全配置
security:
  rate_limit:
    requests_per_minute: 60
    burst: 10
  cors:
    allow_origins: ["*"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["*"]