app:
  name: "xiaohongshu-proxy"
  version: "1.0.0"
  environment: "development"
  host: "localhost"
  port: 8080

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  name: "xiaohongshu_proxy"
  ssl_mode: "disable"
  max_connections: 100
  max_idle_connections: 10

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 100

jwt:
  secret: "your-super-secret-jwt-key"
  expires_in: "24h"

claude:
  api_key: "your-claude-api-key"
  base_url: "https://api.anthropic.com"
  timeout: "30s"
  max_retries: 3

mcp:
  base_url: "http://localhost:18060/mcp"
  timeout: "30s"
  max_connections: 50

container:
  registry: "xiaohongshu-proxy"
  base_port: 19000
  max_per_user: 3
  auto_cleanup: true
  cleanup_interval: "1h"

logging:
  level: "info"
  format: "json"
  output: "stdout"

security:
  rate_limit:
    requests_per_minute: 100
    burst: 200
  cors:
    allow_origins: ["*"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["*"]